spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task02
    username: postgres
    password: alpine
server:
  servlet:
    context-path: /hit